unbind C-b
set -g prefix C-t

unbind r
bind r source-file ~/.tmux.conf

unbind ^T
bind ^T select-pane -t :.+

bind h split-window -v
bind v split-window -h

set -g mouse on
bind-key -T copy-mode MouseDragEnd1Pane send-keys -X copy-pipe-no-clear pbcopy
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-no-clear pbcopy

set -s escape-time 200

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'dracula/tmux'

set -g @dracula-show-powerline 'true'

set -g @dracula-plugins 'cpu-usage ram-usage'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'