[project]
name = "hpc-server-tools"
version = "0.1.0"
description = "Server Side Toolkit for HHU HPC Hilbert"
authors = [{ name = "Carel van Niekerk", email = "cvanniekerk@hhu.de" }]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gpustat >= 1.1.1",
    "psutil >= 6.0.0",
    "types-psutil>=6.1.0.20241221",
    "rich >= 13.7.1",
]

[build-system]
requires = ["uv_build>=0.8.8,<0.9.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "hpc-server-tools"
module-root = ""
