[project]
name = "hpc-server-tools"
version = "0.2.0"
description = "Server Side Toolkit for Lamarr Cluster"
authors = [{ name = "Carel van Niekerk", email = "cvanniekerk@hhu.de" }]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gpustat >= 1.1.1",
    "psutil >= 6.1.0",
    "types-psutil>=6.1.0.20241221",
    "rich >= 13.7.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
